// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnboardingApp.Api.Data;

#nullable disable

namespace OnboardingApp.Api.Migrations
{
    [DbContext(typeof(OnboardingDbContext))]
    [Migration("20260704162036_UpdateTimelinePhaseToWeeks")]
    partial class UpdateTimelinePhaseToWeeks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnboardingApp.Api.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments", t =>
                        {
                            t.HasCheckConstraint("CK_Departments_Name", "\"Name\" IN ('Engineering', 'Sales', 'Marketing', 'HR', 'Finance')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.OnboardingTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("TimelinePhase")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_OnboardingTasks_DepartmentId");

                    b.ToTable("OnboardingTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Description = "Join the company-wide welcome meeting. You will meet the founders, understand Meridian's mission, and get a tour of the office.",
                            DisplayOrder = 1,
                            TimelinePhase = 1,
                            Title = "Attend Day 1 Welcome Session"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Description = "Install the required tools for your workstation: VS Code (or your preferred IDE), Git, Node.js, and the .NET SDK. Follow the setup guide in the internal wiki.",
                            DisplayOrder = 2,
                            TimelinePhase = 1,
                            Title = "Set Up Your Development Environment"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Description = "Request access to the Meridian GitHub organisation from your team lead. Accept the invitation email and confirm you can see the private repositories.",
                            DisplayOrder = 3,
                            TimelinePhase = 1,
                            Title = "Get GitHub Organisation Access"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Description = "Have a 30-minute intro call with your team lead and assigned buddy. Discuss your role, current projects, and how the team operates day-to-day.",
                            DisplayOrder = 4,
                            TimelinePhase = 1,
                            Title = "Meet Your Team Lead & Onboarding Buddy"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 1,
                            Description = "Install Docker Desktop and verify it is running correctly by executing `docker run hello-world` in your terminal. Docker is required to run the local development stack.",
                            DisplayOrder = 1,
                            TimelinePhase = 2,
                            Title = "Install Docker"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 1,
                            Description = "Clone the main backend repository from GitHub and install its dependencies. Follow the README to confirm the project structure looks correct.",
                            DisplayOrder = 2,
                            TimelinePhase = 2,
                            Title = "Clone the Core API Repository"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 1,
                            Description = "Use `docker compose up` to spin up the full local stack (API + database). Verify the API responds at http://localhost:5000/healthz.",
                            DisplayOrder = 3,
                            TimelinePhase = 2,
                            Title = "Run the Application Locally"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 1,
                            Description = "Complete the mandatory security awareness module on the company LMS. This covers data handling policies, password management, and phishing awareness.",
                            DisplayOrder = 4,
                            TimelinePhase = 2,
                            Title = "Complete Security & Compliance Training"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 1,
                            Description = "Pick up a good-first-issue ticket from the backlog, implement the fix or feature, and open a PR against the main branch following the contribution guidelines.",
                            DisplayOrder = 1,
                            TimelinePhase = 3,
                            Title = "Submit Your First Pull Request"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 1,
                            Description = "Review a colleague's open pull request. Leave at least one constructive comment or approval. This helps you understand the codebase and team coding standards.",
                            DisplayOrder = 2,
                            TimelinePhase = 3,
                            Title = "Complete Your First Code Review"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 1,
                            Description = "Participate in the full sprint ceremony cycle: planning, daily stand-ups, review, and retrospective. Share one observation or suggestion during the retro.",
                            DisplayOrder = 3,
                            TimelinePhase = 4,
                            Title = "Attend Sprint Planning & Retrospective"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 2,
                            Description = "Join the company-wide welcome meeting. You will meet the founders, understand Meridian's mission, and get a tour of the office.",
                            DisplayOrder = 1,
                            TimelinePhase = 1,
                            Title = "Attend Day 1 Welcome Session"
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 2,
                            Description = "Log in to the company CRM (Salesforce) using the credentials sent to your work email. Complete your profile and familiarise yourself with the dashboard.",
                            DisplayOrder = 2,
                            TimelinePhase = 1,
                            Title = "Set Up Your CRM Account"
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 2,
                            Description = "Have a 30-minute intro call with your sales manager. Discuss your territory, targets, and the team's current pipeline.",
                            DisplayOrder = 3,
                            TimelinePhase = 1,
                            Title = "Meet Your Sales Manager"
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 2,
                            Description = "Work through the product training modules on the LMS. By the end you should be able to explain Meridian's core offering, pricing tiers, and key differentiators.",
                            DisplayOrder = 1,
                            TimelinePhase = 2,
                            Title = "Complete Product & Service Training"
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 2,
                            Description = "Join a live discovery or demo call as a silent listener. Afterwards, debrief with the rep and note three things you would like to replicate.",
                            DisplayOrder = 2,
                            TimelinePhase = 2,
                            Title = "Shadow a Senior Sales Rep on a Call"
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 2,
                            Description = "Create your first opportunity records in Salesforce. Configure your personal pipeline view and set up task reminders for your first week's outreach.",
                            DisplayOrder = 3,
                            TimelinePhase = 3,
                            Title = "Set Up Your Sales Pipeline in the CRM"
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 2,
                            Description = "Send personalised outreach to at least 10 prospects in your territory using the approved email templates. Log all activity in the CRM.",
                            DisplayOrder = 1,
                            TimelinePhase = 3,
                            Title = "Make Your First Outbound Outreach"
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 2,
                            Description = "Present the current state of your pipeline in a 1:1 with your manager. Discuss deal health, blockers, and what support you need to hit your first target.",
                            DisplayOrder = 2,
                            TimelinePhase = 4,
                            Title = "Review Pipeline with Your Manager"
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 3,
                            Description = "Join the company-wide welcome meeting. You will meet the founders, understand Meridian's mission, and get a tour of the office.",
                            DisplayOrder = 1,
                            TimelinePhase = 1,
                            Title = "Attend Day 1 Welcome Session"
                        },
                        new
                        {
                            Id = 21,
                            DepartmentId = 3,
                            Description = "Request access to HubSpot, Canva, and the shared Google Drive marketing folder from your manager. Verify you can log in to each tool.",
                            DisplayOrder = 2,
                            TimelinePhase = 1,
                            Title = "Get Access to Marketing Tools"
                        },
                        new
                        {
                            Id = 22,
                            DepartmentId = 3,
                            Description = "Read through the Meridian brand playbook (fonts, colours, tone of voice, logo usage). This is your reference for all content you produce.",
                            DisplayOrder = 3,
                            TimelinePhase = 1,
                            Title = "Review Brand Guidelines"
                        },
                        new
                        {
                            Id = 23,
                            DepartmentId = 3,
                            Description = "Review the current quarter's content calendar in Google Sheets. Identify the next three upcoming pieces you might contribute to.",
                            DisplayOrder = 1,
                            TimelinePhase = 2,
                            Title = "Get Familiar with the Content Calendar"
                        },
                        new
                        {
                            Id = 24,
                            DepartmentId = 3,
                            Description = "Work through the internal brand messaging course on the LMS. Complete the short quiz at the end to confirm your understanding.",
                            DisplayOrder = 2,
                            TimelinePhase = 2,
                            Title = "Complete Brand & Messaging Training"
                        },
                        new
                        {
                            Id = 25,
                            DepartmentId = 3,
                            Description = "Take ownership of at least one deliverable in an active marketing campaign — a social post, blog draft, or email copy. Get it reviewed and published.",
                            DisplayOrder = 1,
                            TimelinePhase = 3,
                            Title = "Contribute to an Active Campaign"
                        },
                        new
                        {
                            Id = 26,
                            DepartmentId = 3,
                            Description = "Compile performance metrics for content you have worked on (impressions, clicks, conversions) and present a 5-minute summary to the marketing team.",
                            DisplayOrder = 2,
                            TimelinePhase = 4,
                            Title = "Present Your First Marketing Insights Report"
                        },
                        new
                        {
                            Id = 27,
                            DepartmentId = 4,
                            Description = "Join the company-wide welcome meeting. You will meet the founders, understand Meridian's mission, and get a tour of the office.",
                            DisplayOrder = 1,
                            TimelinePhase = 1,
                            Title = "Attend Day 1 Welcome Session"
                        },
                        new
                        {
                            Id = 28,
                            DepartmentId = 4,
                            Description = "Sign and submit all required employment documents: contract, tax forms, and emergency contact details. Keep digital copies for your records.",
                            DisplayOrder = 2,
                            TimelinePhase = 1,
                            Title = "Complete Employment Paperwork"
                        },
                        new
                        {
                            Id = 29,
                            DepartmentId = 4,
                            Description = "Collect your employee ID badge from reception and confirm access to the HR information system (HRIS) and the payroll portal.",
                            DisplayOrder = 3,
                            TimelinePhase = 1,
                            Title = "Get Your Employee ID & System Access"
                        },
                        new
                        {
                            Id = 30,
                            DepartmentId = 4,
                            Description = "Finish the mandatory compliance modules on the LMS: anti-harassment, GDPR data handling, and workplace safety. All three must be completed within week one.",
                            DisplayOrder = 1,
                            TimelinePhase = 2,
                            Title = "Complete Mandatory Compliance Training"
                        },
                        new
                        {
                            Id = 31,
                            DepartmentId = 4,
                            Description = "Log in to the benefits portal and select your health, dental, and pension options before the enrolment deadline. Contact the benefits provider with any questions.",
                            DisplayOrder = 2,
                            TimelinePhase = 2,
                            Title = "Enrol in Company Benefits"
                        },
                        new
                        {
                            Id = 32,
                            DepartmentId = 4,
                            Description = "Read the employee handbook, leave policy, remote work policy, and code of conduct. Confirm you have reviewed them by signing the acknowledgement form.",
                            DisplayOrder = 3,
                            TimelinePhase = 3,
                            Title = "Review All Company HR Policies"
                        },
                        new
                        {
                            Id = 33,
                            DepartmentId = 4,
                            Description = "Schedule and attend a structured 30-day review with your manager. Discuss your onboarding experience, early wins, and goals for the next two months.",
                            DisplayOrder = 1,
                            TimelinePhase = 4,
                            Title = "Complete 30-Day Check-in with Your Manager"
                        },
                        new
                        {
                            Id = 34,
                            DepartmentId = 5,
                            Description = "Join the company-wide welcome meeting. You will meet the founders, understand Meridian's mission, and get a tour of the office.",
                            DisplayOrder = 1,
                            TimelinePhase = 1,
                            Title = "Attend Day 1 Welcome Session"
                        },
                        new
                        {
                            Id = 35,
                            DepartmentId = 5,
                            Description = "Request access to the accounting software (QuickBooks) and the financial reporting suite from your manager. Verify login and confirm your permission level.",
                            DisplayOrder = 2,
                            TimelinePhase = 1,
                            Title = "Get Access to Financial Systems"
                        },
                        new
                        {
                            Id = 36,
                            DepartmentId = 5,
                            Description = "Have a 30-minute intro call with the Finance Lead. Discuss your responsibilities, the monthly close schedule, and how finance collaborates with other departments.",
                            DisplayOrder = 3,
                            TimelinePhase = 1,
                            Title = "Meet the Finance Team Lead"
                        },
                        new
                        {
                            Id = 37,
                            DepartmentId = 5,
                            Description = "Finish the mandatory financial compliance and anti-fraud training modules on the LMS. Take note of the expense submission deadlines covered in the course.",
                            DisplayOrder = 1,
                            TimelinePhase = 2,
                            Title = "Complete Financial Compliance Training"
                        },
                        new
                        {
                            Id = 38,
                            DepartmentId = 5,
                            Description = "Review the expense policy and submit a test expense report in QuickBooks to verify your access and understand the approval workflow.",
                            DisplayOrder = 2,
                            TimelinePhase = 2,
                            Title = "Understand the Expense Reporting Process"
                        },
                        new
                        {
                            Id = 39,
                            DepartmentId = 5,
                            Description = "Open the standard monthly and quarterly budget report templates in the shared Finance drive. Familiarise yourself with the structure before the next reporting cycle.",
                            DisplayOrder = 3,
                            TimelinePhase = 3,
                            Title = "Review Budget Reporting Templates"
                        },
                        new
                        {
                            Id = 40,
                            DepartmentId = 5,
                            Description = "Take ownership of one section of the monthly financial report. Prepare the data, validate figures with a colleague, and submit it ahead of the close deadline.",
                            DisplayOrder = 1,
                            TimelinePhase = 4,
                            Title = "Contribute to Your First Monthly Report"
                        });
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.TaskPrerequisite", b =>
                {
                    b.Property<int>("PreDependentTaskId")
                        .HasColumnType("integer");

                    b.Property<int>("PostDependentTaskId")
                        .HasColumnType("integer");

                    b.HasKey("PreDependentTaskId", "PostDependentTaskId");

                    b.HasIndex("PostDependentTaskId");

                    b.ToTable("TaskPrerequisites");

                    b.HasData(
                        new
                        {
                            PreDependentTaskId = 5,
                            PostDependentTaskId = 6
                        },
                        new
                        {
                            PreDependentTaskId = 6,
                            PostDependentTaskId = 7
                        },
                        new
                        {
                            PreDependentTaskId = 7,
                            PostDependentTaskId = 9
                        },
                        new
                        {
                            PreDependentTaskId = 9,
                            PostDependentTaskId = 10
                        },
                        new
                        {
                            PreDependentTaskId = 15,
                            PostDependentTaskId = 16
                        },
                        new
                        {
                            PreDependentTaskId = 16,
                            PostDependentTaskId = 18
                        },
                        new
                        {
                            PreDependentTaskId = 24,
                            PostDependentTaskId = 25
                        },
                        new
                        {
                            PreDependentTaskId = 28,
                            PostDependentTaskId = 31
                        },
                        new
                        {
                            PreDependentTaskId = 30,
                            PostDependentTaskId = 33
                        },
                        new
                        {
                            PreDependentTaskId = 38,
                            PostDependentTaskId = 40
                        });
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.OnboardingTask", b =>
                {
                    b.HasOne("OnboardingApp.Api.Models.Department", "Department")
                        .WithMany("OnboardingTasks")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.TaskPrerequisite", b =>
                {
                    b.HasOne("OnboardingApp.Api.Models.OnboardingTask", "PostDependentTask")
                        .WithMany("Prerequisites")
                        .HasForeignKey("PostDependentTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnboardingApp.Api.Models.OnboardingTask", "PreDependentTask")
                        .WithMany("Dependents")
                        .HasForeignKey("PreDependentTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PostDependentTask");

                    b.Navigation("PreDependentTask");
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.Department", b =>
                {
                    b.Navigation("OnboardingTasks");
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.OnboardingTask", b =>
                {
                    b.Navigation("Dependents");

                    b.Navigation("Prerequisites");
                });
#pragma warning restore 612, 618
        }
    }
}
