// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnboardingApp.Api.Data;

#nullable disable

namespace OnboardingApp.Api.Migrations
{
    [DbContext(typeof(OnboardingDbContext))]
    [Migration("20260706113924_AddOnboardingProgress")]
    partial class AddOnboardingProgress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnboardingApp.Api.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FridaySchedule")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("remote");

                    b.Property<string>("MondaySchedule")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("office");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RoleKey")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Tagline")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ThursdaySchedule")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("remote");

                    b.Property<string>("TuesdaySchedule")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("office");

                    b.Property<string>("WednesdaySchedule")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("office");

                    b.Property<string>("WelcomeMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RoleKey")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FridaySchedule = "remote",
                            MondaySchedule = "office",
                            Name = "Engineering",
                            RoleKey = "engineering",
                            Tagline = "Build the future, one commit at a time",
                            ThursdaySchedule = "remote",
                            TuesdaySchedule = "office",
                            WednesdaySchedule = "office",
                            WelcomeMessage = "Welcome to Engineering! We are excited to have you on board. Your first weeks will be all about getting your development environment ready and making your first contribution."
                        },
                        new
                        {
                            Id = 2,
                            FridaySchedule = "office",
                            MondaySchedule = "office",
                            Name = "Sales",
                            RoleKey = "sales",
                            Tagline = "Turn every conversation into an opportunity",
                            ThursdaySchedule = "remote",
                            TuesdaySchedule = "remote",
                            WednesdaySchedule = "office",
                            WelcomeMessage = "Welcome to Sales! You'll be building relationships that drive Meridian's growth. Start by getting familiar with our CRM and shadowing top performers."
                        },
                        new
                        {
                            Id = 3,
                            FridaySchedule = "remote",
                            MondaySchedule = "remote",
                            Name = "Marketing",
                            RoleKey = "marketing",
                            Tagline = "Tell the story that moves the market",
                            ThursdaySchedule = "remote",
                            TuesdaySchedule = "office",
                            WednesdaySchedule = "office",
                            WelcomeMessage = "Welcome to Marketing! You'll shape how the world sees Meridian. Dive into the brand playbook and start exploring our content calendar."
                        },
                        new
                        {
                            Id = 4,
                            FridaySchedule = "remote",
                            MondaySchedule = "office",
                            Name = "HR",
                            RoleKey = "hr",
                            Tagline = "People are our greatest product",
                            ThursdaySchedule = "office",
                            TuesdaySchedule = "office",
                            WednesdaySchedule = "remote",
                            WelcomeMessage = "Welcome to HR! You'll play a key role in helping others succeed at Meridian. Start by completing your paperwork and meeting the team."
                        },
                        new
                        {
                            Id = 5,
                            FridaySchedule = "office",
                            MondaySchedule = "office",
                            Name = "Finance",
                            RoleKey = "finance",
                            Tagline = "The numbers that keep us moving forward",
                            ThursdaySchedule = "remote",
                            TuesdaySchedule = "office",
                            WednesdaySchedule = "remote",
                            WelcomeMessage = "Welcome to Finance! Your work ensures Meridian's fiscal health. Get started by gaining system access and meeting the finance team."
                        });
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.DepartmentContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarInitials")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GoogleMeetUrl")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PreferredCommTool")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("slack");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SlackMemberId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_DepartmentContacts_DepartmentId");

                    b.ToTable("DepartmentContacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarInitials = "PS",
                            Bio = "Leads the backend platform team. Open-source enthusiast and conference speaker.",
                            DepartmentId = 1,
                            DisplayOrder = 1,
                            Email = "priya.sharma@meridian.io",
                            GoogleMeetUrl = "https://meet.google.com/pri-ya-sharma",
                            Name = "Priya Sharma",
                            PreferredCommTool = "slack",
                            Role = "Engineering Manager",
                            SlackMemberId = "U012345678A"
                        },
                        new
                        {
                            Id = 2,
                            AvatarInitials = "LO",
                            Bio = "Your onboarding buddy. Go-to for architecture questions and code reviews.",
                            DepartmentId = 1,
                            DisplayOrder = 2,
                            Email = "liam.obrien@meridian.io",
                            GoogleMeetUrl = "https://meet.google.com/lia-m-obrien",
                            Name = "Liam O'Brien",
                            PreferredCommTool = "meet",
                            Role = "Senior Engineer",
                            SlackMemberId = "U012345678B"
                        },
                        new
                        {
                            Id = 3,
                            AvatarInitials = "YT",
                            Bio = "Owns CI/CD pipelines and cloud infrastructure. Ask her about the deployment process.",
                            DepartmentId = 1,
                            DisplayOrder = 3,
                            Email = "yuki.tanaka@meridian.io",
                            GoogleMeetUrl = "https://meet.google.com/yuk-i-tanaka",
                            Name = "Yuki Tanaka",
                            PreferredCommTool = "slack",
                            Role = "DevOps Engineer",
                            SlackMemberId = "U012345678C"
                        },
                        new
                        {
                            Id = 4,
                            AvatarInitials = "MW",
                            Bio = "Leads the EMEA sales team. Passionate about consultative selling.",
                            DepartmentId = 2,
                            DisplayOrder = 1,
                            Email = "marcus.webb@meridian.io",
                            GoogleMeetUrl = "https://meet.google.com/mar-c-us-webb",
                            Name = "Marcus Webb",
                            PreferredCommTool = "meet",
                            Role = "Sales Manager",
                            SlackMemberId = "U022345678A"
                        },
                        new
                        {
                            Id = 5,
                            AvatarInitials = "SR",
                            Bio = "Your onboarding buddy. Top performer in enterprise deals.",
                            DepartmentId = 2,
                            DisplayOrder = 2,
                            Email = "sofia.reyes@meridian.io",
                            GoogleMeetUrl = "https://meet.google.com/sof-i-a-reyes",
                            Name = "Sofia Reyes",
                            PreferredCommTool = "slack",
                            Role = "Account Executive",
                            SlackMemberId = "U022345678B"
                        },
                        new
                        {
                            Id = 6,
                            AvatarInitials = "JO",
                            Bio = "Manages inbound pipeline and prospect qualification.",
                            DepartmentId = 2,
                            DisplayOrder = 3,
                            Email = "james.okafor@meridian.io",
                            GoogleMeetUrl = "https://meet.google.com/jam-e-s-okafor",
                            Name = "James Okafor",
                            PreferredCommTool = "slack",
                            Role = "Sales Development Rep",
                            SlackMemberId = "U022345678C"
                        },
                        new
                        {
                            Id = 7,
                            AvatarInitials = "AD",
                            Bio = "Drives brand strategy and growth campaigns across all channels.",
                            DepartmentId = 3,
                            DisplayOrder = 1,
                            Email = "amara.diallo@meridian.io",
                            GoogleMeetUrl = "https://meet.google.com/ama-r-a-diallo",
                            Name = "Amara Diallo",
                            PreferredCommTool = "meet",
                            Role = "Head of Marketing",
                            SlackMemberId = "U032345678A"
                        },
                        new
                        {
                            Id = 8,
                            AvatarInitials = "CP",
                            Bio = "Your onboarding buddy. Owns the content calendar and editorial voice.",
                            DepartmentId = 3,
                            DisplayOrder = 2,
                            Email = "chris.park@meridian.io",
                            GoogleMeetUrl = "https://meet.google.com/chr-i-s-park",
                            Name = "Chris Park",
                            PreferredCommTool = "slack",
                            Role = "Content Strategist",
                            SlackMemberId = "U032345678B"
                        },
                        new
                        {
                            Id = 9,
                            AvatarInitials = "EM",
                            Bio = "Runs paid acquisition campaigns and analyses conversion metrics.",
                            DepartmentId = 3,
                            DisplayOrder = 3,
                            Email = "elena.morel@meridian.io",
                            GoogleMeetUrl = "https://meet.google.com/ele-n-a-morel",
                            Name = "Elena Morel",
                            PreferredCommTool = "slack",
                            Role = "Performance Marketer",
                            SlackMemberId = "U032345678C"
                        },
                        new
                        {
                            Id = 10,
                            AvatarInitials = "DK",
                            Bio = "Oversees talent acquisition, L&D, and employee experience.",
                            DepartmentId = 4,
                            DisplayOrder = 1,
                            Email = "david.kim@meridian.io",
                            GoogleMeetUrl = "https://meet.google.com/dav-i-d-kim",
                            Name = "David Kim",
                            PreferredCommTool = "meet",
                            Role = "HR Director",
                            SlackMemberId = "U042345678A"
                        },
                        new
                        {
                            Id = 11,
                            AvatarInitials = "FA",
                            Bio = "Your onboarding buddy. Manages benefits, compliance, and HR ops.",
                            DepartmentId = 4,
                            DisplayOrder = 2,
                            Email = "fatima.alsayed@meridian.io",
                            GoogleMeetUrl = "https://meet.google.com/fat-i-m-a",
                            Name = "Fatima Al-Sayed",
                            PreferredCommTool = "slack",
                            Role = "People Operations Lead",
                            SlackMemberId = "U042345678B"
                        },
                        new
                        {
                            Id = 12,
                            AvatarInitials = "TB",
                            Bio = "Leads recruiting efforts across all departments.",
                            DepartmentId = 4,
                            DisplayOrder = 3,
                            Email = "tom.brennan@meridian.io",
                            GoogleMeetUrl = "https://meet.google.com/tom-bren-nan",
                            Name = "Tom Brennan",
                            PreferredCommTool = "slack",
                            Role = "Talent Acquisition Spec.",
                            SlackMemberId = "U042345678C"
                        },
                        new
                        {
                            Id = 13,
                            AvatarInitials = "NP",
                            Bio = "Owns financial reporting, forecasting, and budget cycles.",
                            DepartmentId = 5,
                            DisplayOrder = 1,
                            Email = "nadia.petrov@meridian.io",
                            GoogleMeetUrl = "https://meet.google.com/nad-i-a-petrov",
                            Name = "Nadia Petrov",
                            PreferredCommTool = "meet",
                            Role = "Finance Lead",
                            SlackMemberId = "U052345678A"
                        },
                        new
                        {
                            Id = 14,
                            AvatarInitials = "AM",
                            Bio = "Your onboarding buddy. Specialises in expense reporting and financial modelling.",
                            DepartmentId = 5,
                            DisplayOrder = 2,
                            Email = "arjun.mehta@meridian.io",
                            GoogleMeetUrl = "https://meet.google.com/arj-u-n-mehta",
                            Name = "Arjun Mehta",
                            PreferredCommTool = "slack",
                            Role = "Financial Analyst",
                            SlackMemberId = "U052345678B"
                        },
                        new
                        {
                            Id = 15,
                            AvatarInitials = "LB",
                            Bio = "Handles payroll processing and employee compensation queries.",
                            DepartmentId = 5,
                            DisplayOrder = 3,
                            Email = "laura.bennett@meridian.io",
                            GoogleMeetUrl = "https://meet.google.com/lau-r-a-bennett",
                            Name = "Laura Bennett",
                            PreferredCommTool = "slack",
                            Role = "Payroll Specialist",
                            SlackMemberId = "U052345678C"
                        });
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.OnboardingProgress", b =>
                {
                    b.Property<Guid>("SessionToken")
                        .HasColumnType("uuid");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.HasKey("SessionToken", "TaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("OnboardingProgresses");
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.OnboardingTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("TimelinePhase")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_OnboardingTasks_DepartmentId");

                    b.ToTable("OnboardingTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Description = "Join the company-wide welcome meeting. You will meet the founders, understand Meridian's mission, and get a tour of the office.",
                            DisplayOrder = 1,
                            TimelinePhase = 1,
                            Title = "Attend Day 1 Welcome Session"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Description = "Install the required tools for your workstation: VS Code (or your preferred IDE), Git, Node.js, and the .NET SDK. Follow the setup guide in the internal wiki.",
                            DisplayOrder = 2,
                            TimelinePhase = 1,
                            Title = "Set Up Your Development Environment"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Description = "Request access to the Meridian GitHub organisation from your team lead. Accept the invitation email and confirm you can see the private repositories.",
                            DisplayOrder = 3,
                            TimelinePhase = 1,
                            Title = "Get GitHub Organisation Access"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Description = "Have a 30-minute intro call with your team lead and assigned buddy. Discuss your role, current projects, and how the team operates day-to-day.",
                            DisplayOrder = 4,
                            TimelinePhase = 1,
                            Title = "Meet Your Team Lead & Onboarding Buddy"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 1,
                            Description = "Install Docker Desktop and verify it is running correctly by executing `docker run hello-world` in your terminal. Docker is required to run the local development stack.",
                            DisplayOrder = 1,
                            TimelinePhase = 2,
                            Title = "Install Docker"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 1,
                            Description = "Clone the main backend repository from GitHub and install its dependencies. Follow the README to confirm the project structure looks correct.",
                            DisplayOrder = 2,
                            TimelinePhase = 2,
                            Title = "Clone the Core API Repository"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 1,
                            Description = "Use `docker compose up` to spin up the full local stack (API + database). Verify the API responds at http://localhost:5000/healthz.",
                            DisplayOrder = 3,
                            TimelinePhase = 2,
                            Title = "Run the Application Locally"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 1,
                            Description = "Complete the mandatory security awareness module on the company LMS. This covers data handling policies, password management, and phishing awareness.",
                            DisplayOrder = 4,
                            TimelinePhase = 2,
                            Title = "Complete Security & Compliance Training"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 1,
                            Description = "Pick up a good-first-issue ticket from the backlog, implement the fix or feature, and open a PR against the main branch following the contribution guidelines.",
                            DisplayOrder = 1,
                            TimelinePhase = 3,
                            Title = "Submit Your First Pull Request"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 1,
                            Description = "Review a colleague's open pull request. Leave at least one constructive comment or approval. This helps you understand the codebase and team coding standards.",
                            DisplayOrder = 2,
                            TimelinePhase = 3,
                            Title = "Complete Your First Code Review"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 1,
                            Description = "Participate in the full sprint ceremony cycle: planning, daily stand-ups, review, and retrospective. Share one observation or suggestion during the retro.",
                            DisplayOrder = 3,
                            TimelinePhase = 4,
                            Title = "Attend Sprint Planning & Retrospective"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 2,
                            Description = "Join the company-wide welcome meeting. You will meet the founders, understand Meridian's mission, and get a tour of the office.",
                            DisplayOrder = 1,
                            TimelinePhase = 1,
                            Title = "Attend Day 1 Welcome Session"
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 2,
                            Description = "Log in to the company CRM (Salesforce) using the credentials sent to your work email. Complete your profile and familiarise yourself with the dashboard.",
                            DisplayOrder = 2,
                            TimelinePhase = 1,
                            Title = "Set Up Your CRM Account"
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 2,
                            Description = "Have a 30-minute intro call with your sales manager. Discuss your territory, targets, and the team's current pipeline.",
                            DisplayOrder = 3,
                            TimelinePhase = 1,
                            Title = "Meet Your Sales Manager"
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 2,
                            Description = "Work through the product training modules on the LMS. By the end you should be able to explain Meridian's core offering, pricing tiers, and key differentiators.",
                            DisplayOrder = 1,
                            TimelinePhase = 2,
                            Title = "Complete Product & Service Training"
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 2,
                            Description = "Join a live discovery or demo call as a silent listener. Afterwards, debrief with the rep and note three things you would like to replicate.",
                            DisplayOrder = 2,
                            TimelinePhase = 2,
                            Title = "Shadow a Senior Sales Rep on a Call"
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 2,
                            Description = "Create your first opportunity records in Salesforce. Configure your personal pipeline view and set up task reminders for your first week's outreach.",
                            DisplayOrder = 3,
                            TimelinePhase = 3,
                            Title = "Set Up Your Sales Pipeline in the CRM"
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 2,
                            Description = "Send personalised outreach to at least 10 prospects in your territory using the approved email templates. Log all activity in the CRM.",
                            DisplayOrder = 1,
                            TimelinePhase = 3,
                            Title = "Make Your First Outbound Outreach"
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 2,
                            Description = "Present the current state of your pipeline in a 1:1 with your manager. Discuss deal health, blockers, and what support you need to hit your first target.",
                            DisplayOrder = 2,
                            TimelinePhase = 4,
                            Title = "Review Pipeline with Your Manager"
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 3,
                            Description = "Join the company-wide welcome meeting. You will meet the founders, understand Meridian's mission, and get a tour of the office.",
                            DisplayOrder = 1,
                            TimelinePhase = 1,
                            Title = "Attend Day 1 Welcome Session"
                        },
                        new
                        {
                            Id = 21,
                            DepartmentId = 3,
                            Description = "Request access to HubSpot, Canva, and the shared Google Drive marketing folder from your manager. Verify you can log in to each tool.",
                            DisplayOrder = 2,
                            TimelinePhase = 1,
                            Title = "Get Access to Marketing Tools"
                        },
                        new
                        {
                            Id = 22,
                            DepartmentId = 3,
                            Description = "Read through the Meridian brand playbook (fonts, colours, tone of voice, logo usage). This is your reference for all content you produce.",
                            DisplayOrder = 3,
                            TimelinePhase = 1,
                            Title = "Review Brand Guidelines"
                        },
                        new
                        {
                            Id = 23,
                            DepartmentId = 3,
                            Description = "Review the current quarter's content calendar in Google Sheets. Identify the next three upcoming pieces you might contribute to.",
                            DisplayOrder = 1,
                            TimelinePhase = 2,
                            Title = "Get Familiar with the Content Calendar"
                        },
                        new
                        {
                            Id = 24,
                            DepartmentId = 3,
                            Description = "Work through the internal brand messaging course on the LMS. Complete the short quiz at the end to confirm your understanding.",
                            DisplayOrder = 2,
                            TimelinePhase = 2,
                            Title = "Complete Brand & Messaging Training"
                        },
                        new
                        {
                            Id = 25,
                            DepartmentId = 3,
                            Description = "Take ownership of at least one deliverable in an active marketing campaign — a social post, blog draft, or email copy. Get it reviewed and published.",
                            DisplayOrder = 1,
                            TimelinePhase = 3,
                            Title = "Contribute to an Active Campaign"
                        },
                        new
                        {
                            Id = 26,
                            DepartmentId = 3,
                            Description = "Compile performance metrics for content you have worked on (impressions, clicks, conversions) and present a 5-minute summary to the marketing team.",
                            DisplayOrder = 2,
                            TimelinePhase = 4,
                            Title = "Present Your First Marketing Insights Report"
                        },
                        new
                        {
                            Id = 27,
                            DepartmentId = 4,
                            Description = "Join the company-wide welcome meeting. You will meet the founders, understand Meridian's mission, and get a tour of the office.",
                            DisplayOrder = 1,
                            TimelinePhase = 1,
                            Title = "Attend Day 1 Welcome Session"
                        },
                        new
                        {
                            Id = 28,
                            DepartmentId = 4,
                            Description = "Sign and submit all required employment documents: contract, tax forms, and emergency contact details. Keep digital copies for your records.",
                            DisplayOrder = 2,
                            TimelinePhase = 1,
                            Title = "Complete Employment Paperwork"
                        },
                        new
                        {
                            Id = 29,
                            DepartmentId = 4,
                            Description = "Collect your employee ID badge from reception and confirm access to the HR information system (HRIS) and the payroll portal.",
                            DisplayOrder = 3,
                            TimelinePhase = 1,
                            Title = "Get Your Employee ID & System Access"
                        },
                        new
                        {
                            Id = 30,
                            DepartmentId = 4,
                            Description = "Finish the mandatory compliance modules on the LMS: anti-harassment, GDPR data handling, and workplace safety. All three must be completed within week one.",
                            DisplayOrder = 1,
                            TimelinePhase = 2,
                            Title = "Complete Mandatory Compliance Training"
                        },
                        new
                        {
                            Id = 31,
                            DepartmentId = 4,
                            Description = "Log in to the benefits portal and select your health, dental, and pension options before the enrolment deadline. Contact the benefits provider with any questions.",
                            DisplayOrder = 2,
                            TimelinePhase = 2,
                            Title = "Enrol in Company Benefits"
                        },
                        new
                        {
                            Id = 32,
                            DepartmentId = 4,
                            Description = "Read the employee handbook, leave policy, remote work policy, and code of conduct. Confirm you have reviewed them by signing the acknowledgement form.",
                            DisplayOrder = 3,
                            TimelinePhase = 3,
                            Title = "Review All Company HR Policies"
                        },
                        new
                        {
                            Id = 33,
                            DepartmentId = 4,
                            Description = "Schedule and attend a structured 30-day review with your manager. Discuss your onboarding experience, early wins, and goals for the next two months.",
                            DisplayOrder = 1,
                            TimelinePhase = 4,
                            Title = "Complete 30-Day Check-in with Your Manager"
                        },
                        new
                        {
                            Id = 34,
                            DepartmentId = 5,
                            Description = "Join the company-wide welcome meeting. You will meet the founders, understand Meridian's mission, and get a tour of the office.",
                            DisplayOrder = 1,
                            TimelinePhase = 1,
                            Title = "Attend Day 1 Welcome Session"
                        },
                        new
                        {
                            Id = 35,
                            DepartmentId = 5,
                            Description = "Request access to the accounting software (QuickBooks) and the financial reporting suite from your manager. Verify login and confirm your permission level.",
                            DisplayOrder = 2,
                            TimelinePhase = 1,
                            Title = "Get Access to Financial Systems"
                        },
                        new
                        {
                            Id = 36,
                            DepartmentId = 5,
                            Description = "Have a 30-minute intro call with the Finance Lead. Discuss your responsibilities, the monthly close schedule, and how finance collaborates with other departments.",
                            DisplayOrder = 3,
                            TimelinePhase = 1,
                            Title = "Meet the Finance Team Lead"
                        },
                        new
                        {
                            Id = 37,
                            DepartmentId = 5,
                            Description = "Finish the mandatory financial compliance and anti-fraud training modules on the LMS. Take note of the expense submission deadlines covered in the course.",
                            DisplayOrder = 1,
                            TimelinePhase = 2,
                            Title = "Complete Financial Compliance Training"
                        },
                        new
                        {
                            Id = 38,
                            DepartmentId = 5,
                            Description = "Review the expense policy and submit a test expense report in QuickBooks to verify your access and understand the approval workflow.",
                            DisplayOrder = 2,
                            TimelinePhase = 2,
                            Title = "Understand the Expense Reporting Process"
                        },
                        new
                        {
                            Id = 39,
                            DepartmentId = 5,
                            Description = "Open the standard monthly and quarterly budget report templates in the shared Finance drive. Familiarise yourself with the structure before the next reporting cycle.",
                            DisplayOrder = 3,
                            TimelinePhase = 3,
                            Title = "Review Budget Reporting Templates"
                        },
                        new
                        {
                            Id = 40,
                            DepartmentId = 5,
                            Description = "Take ownership of one section of the monthly financial report. Prepare the data, validate figures with a colleague, and submit it ahead of the close deadline.",
                            DisplayOrder = 1,
                            TimelinePhase = 4,
                            Title = "Contribute to Your First Monthly Report"
                        });
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.TaskInstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskInstructions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StepNumber = 1,
                            TaskId = 1,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 2,
                            StepNumber = 2,
                            TaskId = 1,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 3,
                            StepNumber = 3,
                            TaskId = 1,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 4,
                            StepNumber = 1,
                            TaskId = 2,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 5,
                            StepNumber = 2,
                            TaskId = 2,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 6,
                            StepNumber = 3,
                            TaskId = 2,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 7,
                            StepNumber = 1,
                            TaskId = 3,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 8,
                            StepNumber = 2,
                            TaskId = 3,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 9,
                            StepNumber = 3,
                            TaskId = 3,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 10,
                            StepNumber = 1,
                            TaskId = 4,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 11,
                            StepNumber = 2,
                            TaskId = 4,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 12,
                            StepNumber = 3,
                            TaskId = 4,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 13,
                            StepNumber = 1,
                            TaskId = 5,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 14,
                            StepNumber = 2,
                            TaskId = 5,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 15,
                            StepNumber = 3,
                            TaskId = 5,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 16,
                            StepNumber = 1,
                            TaskId = 6,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 17,
                            StepNumber = 2,
                            TaskId = 6,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 18,
                            StepNumber = 3,
                            TaskId = 6,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 19,
                            StepNumber = 1,
                            TaskId = 7,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 20,
                            StepNumber = 2,
                            TaskId = 7,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 21,
                            StepNumber = 3,
                            TaskId = 7,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 22,
                            StepNumber = 1,
                            TaskId = 8,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 23,
                            StepNumber = 2,
                            TaskId = 8,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 24,
                            StepNumber = 3,
                            TaskId = 8,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 25,
                            StepNumber = 1,
                            TaskId = 9,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 26,
                            StepNumber = 2,
                            TaskId = 9,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 27,
                            StepNumber = 3,
                            TaskId = 9,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 28,
                            StepNumber = 1,
                            TaskId = 10,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 29,
                            StepNumber = 2,
                            TaskId = 10,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 30,
                            StepNumber = 3,
                            TaskId = 10,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 31,
                            StepNumber = 1,
                            TaskId = 11,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 32,
                            StepNumber = 2,
                            TaskId = 11,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 33,
                            StepNumber = 3,
                            TaskId = 11,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 34,
                            StepNumber = 1,
                            TaskId = 12,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 35,
                            StepNumber = 2,
                            TaskId = 12,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 36,
                            StepNumber = 3,
                            TaskId = 12,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 37,
                            StepNumber = 1,
                            TaskId = 13,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 38,
                            StepNumber = 2,
                            TaskId = 13,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 39,
                            StepNumber = 3,
                            TaskId = 13,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 40,
                            StepNumber = 1,
                            TaskId = 14,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 41,
                            StepNumber = 2,
                            TaskId = 14,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 42,
                            StepNumber = 3,
                            TaskId = 14,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 43,
                            StepNumber = 1,
                            TaskId = 15,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 44,
                            StepNumber = 2,
                            TaskId = 15,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 45,
                            StepNumber = 3,
                            TaskId = 15,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 46,
                            StepNumber = 1,
                            TaskId = 16,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 47,
                            StepNumber = 2,
                            TaskId = 16,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 48,
                            StepNumber = 3,
                            TaskId = 16,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 49,
                            StepNumber = 1,
                            TaskId = 17,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 50,
                            StepNumber = 2,
                            TaskId = 17,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 51,
                            StepNumber = 3,
                            TaskId = 17,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 52,
                            StepNumber = 1,
                            TaskId = 18,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 53,
                            StepNumber = 2,
                            TaskId = 18,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 54,
                            StepNumber = 3,
                            TaskId = 18,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 55,
                            StepNumber = 1,
                            TaskId = 19,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 56,
                            StepNumber = 2,
                            TaskId = 19,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 57,
                            StepNumber = 3,
                            TaskId = 19,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 58,
                            StepNumber = 1,
                            TaskId = 20,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 59,
                            StepNumber = 2,
                            TaskId = 20,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 60,
                            StepNumber = 3,
                            TaskId = 20,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 61,
                            StepNumber = 1,
                            TaskId = 21,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 62,
                            StepNumber = 2,
                            TaskId = 21,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 63,
                            StepNumber = 3,
                            TaskId = 21,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 64,
                            StepNumber = 1,
                            TaskId = 22,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 65,
                            StepNumber = 2,
                            TaskId = 22,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 66,
                            StepNumber = 3,
                            TaskId = 22,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 67,
                            StepNumber = 1,
                            TaskId = 23,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 68,
                            StepNumber = 2,
                            TaskId = 23,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 69,
                            StepNumber = 3,
                            TaskId = 23,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 70,
                            StepNumber = 1,
                            TaskId = 24,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 71,
                            StepNumber = 2,
                            TaskId = 24,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 72,
                            StepNumber = 3,
                            TaskId = 24,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 73,
                            StepNumber = 1,
                            TaskId = 25,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 74,
                            StepNumber = 2,
                            TaskId = 25,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 75,
                            StepNumber = 3,
                            TaskId = 25,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 76,
                            StepNumber = 1,
                            TaskId = 26,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 77,
                            StepNumber = 2,
                            TaskId = 26,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 78,
                            StepNumber = 3,
                            TaskId = 26,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 79,
                            StepNumber = 1,
                            TaskId = 27,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 80,
                            StepNumber = 2,
                            TaskId = 27,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 81,
                            StepNumber = 3,
                            TaskId = 27,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 82,
                            StepNumber = 1,
                            TaskId = 28,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 83,
                            StepNumber = 2,
                            TaskId = 28,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 84,
                            StepNumber = 3,
                            TaskId = 28,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 85,
                            StepNumber = 1,
                            TaskId = 29,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 86,
                            StepNumber = 2,
                            TaskId = 29,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 87,
                            StepNumber = 3,
                            TaskId = 29,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 88,
                            StepNumber = 1,
                            TaskId = 30,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 89,
                            StepNumber = 2,
                            TaskId = 30,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 90,
                            StepNumber = 3,
                            TaskId = 30,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 91,
                            StepNumber = 1,
                            TaskId = 31,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 92,
                            StepNumber = 2,
                            TaskId = 31,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 93,
                            StepNumber = 3,
                            TaskId = 31,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 94,
                            StepNumber = 1,
                            TaskId = 32,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 95,
                            StepNumber = 2,
                            TaskId = 32,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 96,
                            StepNumber = 3,
                            TaskId = 32,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 97,
                            StepNumber = 1,
                            TaskId = 33,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 98,
                            StepNumber = 2,
                            TaskId = 33,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 99,
                            StepNumber = 3,
                            TaskId = 33,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 100,
                            StepNumber = 1,
                            TaskId = 34,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 101,
                            StepNumber = 2,
                            TaskId = 34,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 102,
                            StepNumber = 3,
                            TaskId = 34,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 103,
                            StepNumber = 1,
                            TaskId = 35,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 104,
                            StepNumber = 2,
                            TaskId = 35,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 105,
                            StepNumber = 3,
                            TaskId = 35,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 106,
                            StepNumber = 1,
                            TaskId = 36,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 107,
                            StepNumber = 2,
                            TaskId = 36,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 108,
                            StepNumber = 3,
                            TaskId = 36,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 109,
                            StepNumber = 1,
                            TaskId = 37,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 110,
                            StepNumber = 2,
                            TaskId = 37,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 111,
                            StepNumber = 3,
                            TaskId = 37,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 112,
                            StepNumber = 1,
                            TaskId = 38,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 113,
                            StepNumber = 2,
                            TaskId = 38,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 114,
                            StepNumber = 3,
                            TaskId = 38,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 115,
                            StepNumber = 1,
                            TaskId = 39,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 116,
                            StepNumber = 2,
                            TaskId = 39,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 117,
                            StepNumber = 3,
                            TaskId = 39,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        },
                        new
                        {
                            Id = 118,
                            StepNumber = 1,
                            TaskId = 40,
                            Text = "Read and understand all requirements for this task."
                        },
                        new
                        {
                            Id = 119,
                            StepNumber = 2,
                            TaskId = 40,
                            Text = "Sync with your onboarding buddy or team lead if any blockers arise."
                        },
                        new
                        {
                            Id = 120,
                            StepNumber = 3,
                            TaskId = 40,
                            Text = "Verify and check off the item in your workspace dashboard once done."
                        });
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.TaskPrerequisite", b =>
                {
                    b.Property<int>("PreDependentTaskId")
                        .HasColumnType("integer");

                    b.Property<int>("PostDependentTaskId")
                        .HasColumnType("integer");

                    b.HasKey("PreDependentTaskId", "PostDependentTaskId");

                    b.HasIndex("PostDependentTaskId");

                    b.ToTable("TaskPrerequisites");

                    b.HasData(
                        new
                        {
                            PreDependentTaskId = 5,
                            PostDependentTaskId = 6
                        },
                        new
                        {
                            PreDependentTaskId = 6,
                            PostDependentTaskId = 7
                        },
                        new
                        {
                            PreDependentTaskId = 7,
                            PostDependentTaskId = 9
                        },
                        new
                        {
                            PreDependentTaskId = 9,
                            PostDependentTaskId = 10
                        },
                        new
                        {
                            PreDependentTaskId = 15,
                            PostDependentTaskId = 16
                        },
                        new
                        {
                            PreDependentTaskId = 16,
                            PostDependentTaskId = 18
                        },
                        new
                        {
                            PreDependentTaskId = 24,
                            PostDependentTaskId = 25
                        },
                        new
                        {
                            PreDependentTaskId = 28,
                            PostDependentTaskId = 31
                        },
                        new
                        {
                            PreDependentTaskId = 30,
                            PostDependentTaskId = 33
                        },
                        new
                        {
                            PreDependentTaskId = 38,
                            PostDependentTaskId = 40
                        });
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.DepartmentContact", b =>
                {
                    b.HasOne("OnboardingApp.Api.Models.Department", "Department")
                        .WithMany("Contacts")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.OnboardingProgress", b =>
                {
                    b.HasOne("OnboardingApp.Api.Models.OnboardingTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.OnboardingTask", b =>
                {
                    b.HasOne("OnboardingApp.Api.Models.Department", "Department")
                        .WithMany("OnboardingTasks")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.TaskInstruction", b =>
                {
                    b.HasOne("OnboardingApp.Api.Models.OnboardingTask", "Task")
                        .WithMany("Instructions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.TaskPrerequisite", b =>
                {
                    b.HasOne("OnboardingApp.Api.Models.OnboardingTask", "PostDependentTask")
                        .WithMany("Prerequisites")
                        .HasForeignKey("PostDependentTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnboardingApp.Api.Models.OnboardingTask", "PreDependentTask")
                        .WithMany("Dependents")
                        .HasForeignKey("PreDependentTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PostDependentTask");

                    b.Navigation("PreDependentTask");
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.Department", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("OnboardingTasks");
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.OnboardingTask", b =>
                {
                    b.Navigation("Dependents");

                    b.Navigation("Instructions");

                    b.Navigation("Prerequisites");
                });
#pragma warning restore 612, 618
        }
    }
}
