// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnboardingApp.Api.Data;

#nullable disable

namespace OnboardingApp.Api.Migrations
{
    [DbContext(typeof(OnboardingDbContext))]
    [Migration("20260704123336_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnboardingApp.Api.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments", t =>
                        {
                            t.HasCheckConstraint("CK_Departments_Name", "\"Name\" IN ('Engineering', 'Sales', 'Marketing', 'HR', 'Finance')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.OnboardingTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("TimelinePhase")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_OnboardingTasks_DepartmentId");

                    b.ToTable("OnboardingTasks");
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.TaskPrerequisite", b =>
                {
                    b.Property<int>("PreDependentTaskId")
                        .HasColumnType("integer");

                    b.Property<int>("PostDependentTaskId")
                        .HasColumnType("integer");

                    b.HasKey("PreDependentTaskId", "PostDependentTaskId");

                    b.HasIndex("PostDependentTaskId");

                    b.ToTable("TaskPrerequisites");
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.OnboardingTask", b =>
                {
                    b.HasOne("OnboardingApp.Api.Models.Department", "Department")
                        .WithMany("OnboardingTasks")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.TaskPrerequisite", b =>
                {
                    b.HasOne("OnboardingApp.Api.Models.OnboardingTask", "PostDependentTask")
                        .WithMany("Prerequisites")
                        .HasForeignKey("PostDependentTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnboardingApp.Api.Models.OnboardingTask", "PreDependentTask")
                        .WithMany("Dependents")
                        .HasForeignKey("PreDependentTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PostDependentTask");

                    b.Navigation("PreDependentTask");
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.Department", b =>
                {
                    b.Navigation("OnboardingTasks");
                });

            modelBuilder.Entity("OnboardingApp.Api.Models.OnboardingTask", b =>
                {
                    b.Navigation("Dependents");

                    b.Navigation("Prerequisites");
                });
#pragma warning restore 612, 618
        }
    }
}
